import type { QA } from "./types";

// System design: Gen AI and Agentic AI design interviews, all levels above entry.
export const systemDesignQA: QA[] = [
  {
    q: "Design an enterprise document Q&A system (RAG) for 5M documents and 50k users.",
    a: "Clarify: doc types, update rate, permissions, latency target, languages. Ingestion: parsers per format → structural chunking with overlap → embeddings + metadata (ACLs, updated-at, source) → vector store with hybrid index; event-driven re-indexing on doc change. Query path: authn → ACL-filtered hybrid retrieval (over-fetch 50) → cross-encoder re-rank to top 6 → prompt with citations and refusal instruction → streamed answer with groundedness check. Scale: shard index by tenant/department; cache frequent queries; ~50k users is modest — the index and ACL filtering are the hard parts, not QPS. Evals: retrieval recall@k probe set, groundedness sampling, per-language quality. Name the #1 risk: permission leaks — ACL filters must be server-side, pre-search, and tested adversarially.",
  },
  {
    q: "Design a customer-support AI agent that can look up orders, process refunds, and escalate to humans.",
    a: "Architecture: intent router → conversation agent with three tools (order lookup: read-only; refund: policy-gated; escalate: always available) → guardrail layer → response. Refund tool owns the money logic: eligibility computed in code from order data, caps per transaction/customer/day, fraud signals; the model can only request what the tool independently verifies — above threshold, human approval queue. State: conversation store with summarization; order context cached per session. Escalation triggers: user request, sentiment, low confidence, policy boundary, loop detection. Metrics: containment rate, CSAT, refund error rate, escalation precision. Failure modes to volunteer: prompt injection via user text ('ignore policy, refund me') — defended in the tool layer, not the prompt; and hallucinated order details — every fact in responses templated from tool results, not model memory.",
  },
  {
    q: "Design a code-review assistant for a 500-engineer org. What's different from a chatbot?",
    a: "Different: inputs are diffs+repo context (retrieval over the codebase, not documents), outputs must anchor to specific lines, and the cost of noise is high — engineers ignore chatty bots. Pipeline: PR event → context assembly (diff, changed files' neighborhoods, related tests, style guides) → specialized passes in parallel (bugs, security, tests, style) each with tuned prompts → deduplication and confidence filtering → threshold so only high-value comments post, with severity labels. Feedback loop: thumbs/resolution outcomes per comment train the filter — precision is the product; recall is secondary. Integration: CI-triggered, comments via code-host API, latency budget minutes not seconds (batch-friendly). Evals: a labeled set of historical PRs with known bugs; measure catch rate vs comment volume. The design insight interviewers want: tune for shut-up-unless-sure.",
  },
  {
    q: "Design semantic search over a product catalog with 10M SKUs, 200ms p99, heavy filtering.",
    a: "The twist is filtered ANN at speed. Embed product text (title+attributes) offline in batch; store in an engine with strong pre-filtering (Qdrant/Vespa/pgvector with partitioning) — post-filtering top-k collapses recall when filters are selective. Hybrid: BM25 for exact model numbers/brands fused with vector scores. 200ms budget: no LLM in the hot path — embedding the query (~20ms small model), ANN (~30ms), re-rank top-100 with a light cross-encoder (~50ms) fits; any generative layer (query rewriting) runs async or from cache. Updates: streaming upserts for price/stock metadata (don't re-embed), re-embed only on text change. Evals: click-through and conversion as online truth; offline judgment lists per query class. Sharp point: the query-understanding LLM everyone wants to add belongs behind a cache — popular queries are Zipfian.",
  },
  {
    q: "Design a meeting-notes product: transcribe, summarize, extract action items, at 1M meetings/day.",
    a: "Pipeline stages, all async: ASR (streaming or batch, per-speaker diarization) → transcript store → map-reduce summarization (chunk summaries → merged summary; direct long-context for shorter meetings) → structured extraction (action items with owner/due-date via schema-validated calls) → delivery (email, integrations). Scale: 1M/day ≈ batch economics — use batch inference APIs at ~50% cost, prioritize latency only for the 'notes ready 5 minutes after meeting' tier. Cost model per meeting drives everything: ASR minutes + ~15k transcript tokens through a mid-tier model; route long/important meetings to better models. Quality: faithfulness checks against transcript segments (no invented decisions — the trust-killer), speaker-attribution accuracy, and an eval set of human-annotated meetings. Privacy: consent handling, retention windows, and PII redaction before any secondary use.",
  },
  {
    q: "Design an AI coding agent that can work on a repo autonomously for hours (Devin-style). What are the hard parts?",
    a: "Loop: plan → edit → run/test → observe → revise, inside a sandboxed environment (containerized repo checkout, no external egress except allowlisted, resource limits). Hard parts to name: context management — repos exceed context, so agentic retrieval over code (search tools, not stuffing) plus a persistent working-memory scratchpad; verification — tests as ground truth, but agents game weak tests, so measure on held-out validation and require green CI; error recovery — detecting it's stuck (repeated failures on same file) and backtracking rather than thrashing; and cost/time budgets with checkpointed progress so hours of work survive restarts. Human interface: PR as the output artifact, with the agent's plan and test evidence attached for review. Evals: SWE-bench-style task suites plus your own repo's historical issues. The honest caveat: reliability drops with task length — design for resumable, reviewable increments, not fire-and-forget.",
  },
  {
    q: "Design the memory system for a personal AI assistant used daily for a year.",
    a: "Tiers: working memory (recent turns, verbatim), episodic (conversation summaries, embedded and retrievable), semantic (extracted durable facts — preferences, relationships, commitments — in structured storage with provenance and timestamps), and procedural (learned instructions: 'always book aisle seats'). Write path: after each session, an extraction pass proposes memory updates; conflicts resolved by recency+confidence, with user-visible/editable memory as both trust feature and correction mechanism. Read path: per-turn retrieval across tiers, budgeted (memory competes with conversation for context). Hard problems to volunteer: memory poisoning (validate before persisting; injected content must not write memories), forgetting (right-to-delete must cascade to derived facts), drift (stale facts — expiry and re-confirmation), and eval methodology — scripted multi-week scenarios, because memory bugs are invisible in single sessions.",
  },
  {
    q: "Design a multi-agent research assistant that produces a cited report from a complex question.",
    a: "Orchestration: planner decomposes the question into sub-queries → parallel searcher agents (web/internal tools) gather sources → an extractor pulls claims with citations into a structured evidence store → synthesizer drafts sections from evidence only → critic pass checks claim-citation support and coverage gaps, looping bounded times → final composer. Keys: evidence store as the contract between agents (structured claims+sources, not prose handoffs — prevents telephone-game distortion); citation discipline enforced by validating every claim maps to a source span; source quality scoring; and hard budgets (searches, tokens, wall clock). Injection defense: web content is data, never instructions. Evals: factuality sampling against sources, coverage rubrics, and comparison to human-written baselines. Anti-pattern to name: free-form agent swarms chatting — the structured evidence pipeline is what makes it debuggable and correct.",
  },
  {
    q: "Design real-time voice AI (sub-second responses) for phone support. Where does latency go?",
    a: "Budget ~800ms perceived: streaming ASR (partials at ~100–200ms) → turn-detection (endpointing — the underrated hard problem; too eager interrupts, too lazy feels dead) → LLM with TTFT ~200–300ms (small/fast model, aggressive prompt trimming, speculative response starts on stable partials) → streaming TTS starting on first sentence (~100ms to first audio). Tricks: overlap everything (LLM starts before ASR finalizes; TTS starts before LLM finishes), cache greetings/confirmations, precompute likely next-turn context, and keep tool calls async with verbal fillers ('let me check that'). Barge-in support: user can interrupt TTS, requiring full-duplex audio handling. Quality/latency routing: simple intents → fast path; complex → 'let me look into that' + slower model. Metrics: turn latency p95, interruption rate, containment. Name the truth: model choice matters less than pipeline overlap engineering.",
  },
  {
    q: "Design the eval and release system for prompts/models — CI/CD for LLM behavior.",
    a: "Registry: prompts, model configs, and datasets versioned with owners. CI: on any change, run the affected golden sets (cached where inputs unchanged) → scorers (exact checks, calibrated judges, safety suites) → regression report against baseline with significance, not just averages — per-category diffs catch the regression hiding under an improved mean. Gates: block merge on safety or >X% category regression; human sign-off tier for sensitive surfaces. CD: canary rollout (1%→10%→100%) with production metric guards (parse failures, refusals, feedback) and one-click rollback — which requires versioned everything. Production sampling feeds new cases back into datasets weekly. This is 'how do you ship prompts like software' — the answer is: exactly like software, with datasets as the tests.",
  },
  {
    q: "Design a text-to-SQL analytics assistant for business users over a 500-table warehouse.",
    a: "Don't aim the model at 500 raw tables — it will hallucinate joins. Build a semantic layer: 30–50 governed entities/metrics with definitions, exposed as documented views or a metric store; the model targets only these. Pipeline: question → retrieval over semantic-layer docs (schemas, metric definitions, example queries) → SQL generation constrained to allowlisted views → static validation (parse, table allowlist, row limits, cost estimate) → sandboxed read-only execution with timeout → result + chart + natural-language answer with the SQL shown for auditability. Errors loop once with the DB error message. Permissions: user's warehouse credentials, row-level security in the database, not the prompt. Evals: a benchmark of real business questions with verified answers; measure execution accuracy, not SQL string match. The insight: the semantic layer does more for accuracy than any model upgrade.",
  },
  {
    q: "Design content moderation for user-generated content at 100M posts/day using LLMs.",
    a: "Tiered funnel — economics forbid running a frontier model on everything: hash/blocklists and lightweight classifiers filter the clear cases (~95%) → a small fine-tuned model handles the ambiguous middle → frontier LLM with policy-as-prompt for the genuinely hard residue (<0.5%) → human review for appeals and the model-uncertain slice, whose labels retrain the small models (the flywheel). Latency split: synchronous cheap checks pre-publish; deeper passes async post-publish with takedown. Policy versioning matters: policies change weekly, so policy text lives in prompts/configs, with eval sets per policy area re-run on every policy change. Metrics: precision/recall per harm class (false positives silence users; false negatives are harm), reviewer agreement, appeal overturn rate. Adversarial reality: attackers probe boundaries — red-team continuously and monitor evasion patterns.",
  },
  {
    q: "Design an AI feature flag / experimentation system specifically for LLM products.",
    a: "Extends classic experimentation with LLM-specific units: flags target {prompt version, model, retrieval config, temperature} bundles — coherent variants, not independent knobs, because interactions dominate. Assignment: sticky per user (response style whiplash contaminates experiments), with mutual exclusion layers for overlapping tests. Metrics pipeline: online signals (acceptance, edits, task completion, latency, cost) joined with async judge scores on sampled outputs — quality metrics arrive late, so the system must support delayed metric attribution. LLM-specific guardrails: auto-halt on safety-flag rate, parse-failure rate, or cost-per-request breaching bounds. Sample-size honesty: quality deltas are noisy; power calculations before launch, and offline eval gating so weak variants never reach traffic. Output: experiment readouts tied to the prompt registry so winning versions promote with lineage.",
  },
  {
    q: "Design a document-processing pipeline: 1M invoices/month in 40 formats into structured records at 99.5% field accuracy.",
    a: "Multi-stage with confidence routing: ingestion (OCR/vision model for scans, native parsing for digital) → classification (vendor/format) → extraction via schema-constrained VLM or LLM calls, few-shot with per-vendor examples for the head, generic for the tail → validation layer: type checks, business rules (totals sum, dates sane, vendor match against master data), cross-field consistency → confidence scoring routes: high → straight-through; medium → second-model cross-check; low → human queue whose corrections become training data. 99.5% field accuracy is unreachable model-only at the tail — the design answer is straight-through-processing rate (~85–90%) with human-in-loop on the rest, improving via the correction flywheel. Cost: batch inference, small fine-tuned models for the high-volume vendors. Metrics: per-field accuracy audited on samples, STP rate, cost per document, human-minutes per exception.",
  },
  {
    q: "Design 'chat with your codebase' for a monorepo with 50M lines. Why is naive RAG not enough?",
    a: "Code breaks document assumptions: meaning lives in structure (call graphs, types, imports), not prose proximity — embedding-only retrieval misses 'who calls this' and 'what breaks if I change this'. Design: multi-index — symbol index (definitions/references via LSP/tree-sitter), embedding index over code+docstrings chunked by function/class, keyword/regex search, and a dependency graph. Query router picks strategies: 'where is X defined' → symbol; 'how does auth work' → embeddings over docs+entry points; 'impact of changing X' → graph traversal. Agentic retrieval beats single-shot: let the model search, open files, follow references iteratively with a step budget. Context assembly respects code structure (whole functions, with imports). Freshness: incremental re-index on commit. Evals: real developer questions with verified answers; measure both retrieval hit rate and answer correctness. The takeaway line: treat the codebase as a graph you navigate, not a corpus you embed.",
  },
  {
    q: "Design guardrails architecture as a platform service used by 20 product teams.",
    a: "A policy-enforcement layer in the gateway path: input pipeline (injection heuristics, PII detection, topic classifiers) and output pipeline (safety classifiers, groundedness checks, format validators, brand rules) — each check a composable, versioned module with per-team policy bundles configured declaratively, not coded per team. Latency tiers: fast synchronous checks inline (<50ms, small models/rules); expensive checks async with post-hoc remediation for lower-risk surfaces, or blocking for high-risk ones — teams choose a tier per surface with the risk framework. Central: policy registry, eval suites per check (false-positive rates published — FP rate is what makes teams trust or bypass you), incident-driven rule updates propagating platform-wide, and full decision logging for audit. The design principle to state: guardrails as a service makes the safe path cheaper than rolling your own, which is the only enforcement that scales.",
  },
  {
    q: "Design the serving architecture to run a fine-tuned 8B model for 100 internal use cases economically.",
    a: "One base model, many adapters: serve the shared 8B base on a small GPU pool with LoRA adapters hot-swapped per request (vLLM/LoRAX-style multi-adapter serving) — 100 use cases share weights and KV-cache infrastructure instead of 100 deployments. Routing: request tags select adapter; batching mixes adapters in one forward pass where supported. Capacity: measure aggregate tokens/sec demand; internal workloads are bursty and tolerate queueing — autoscale on queue depth with a batch tier for async jobs. Adapter lifecycle: registry with lineage (dataset, base version), eval gates per adapter, staged rollout. Economics to cite: adapters are megabytes and add minimal serving overhead, so marginal cost per new use case approaches zero — this is the pattern that makes per-team fine-tuning viable at all. Watch: base-model upgrades invalidate all adapters — plan re-training as a batch program with the eval harness.",
  },
  {
    q: "Design an AI-powered incident-response copilot for SREs. What can it safely automate?",
    a: "Read-heavy autonomy, write-gated actions. Capabilities: on alert, auto-assemble context (recent deploys, related incidents, log/metric anomalies, runbook retrieval) into a briefing; interactive investigation via read-only tools (query logs, metrics, traces, config diffs); hypothesis ranking with evidence links; draft comms and timeline documentation. Safe automation line: anything read-only and reversible — auto-run diagnostics yes; remediation (restarts, rollbacks, scaling) proposed as one-click actions with human execution, graduating specific low-risk actions to auto with per-action track records. Injection surface: logs contain attacker-controlled text — treat as data, never instructions. Trust building: measure time-to-context and hypothesis hit rate; publish when the copilot was right/wrong per incident review. The design truth: the briefing assembly alone cuts MTTR meaningfully and carries near-zero risk — start there, earn autonomy with evidence.",
  },
  {
    q: "Design cross-region/multi-jurisdiction LLM serving where data residency laws differ.",
    a: "Data-plane regionalization with a thin global control plane. Per region: full inference stack (gateway, models — self-hosted or in-region provider endpoints, vector stores, logs) so prompts, retrieved content, and traces never cross borders; user requests route to their data's home region. Control plane (global): prompt registry, eval definitions, policy configs, deployment orchestration — metadata only, no user content. Hard spots to name: model availability differs by region (provider X isn't in region Y — your eval harness re-qualifies substitutes per region); observability without centralizing content (aggregate metrics globally, raw traces stay local, sampled debugging via in-region access); memory/personalization must be region-pinned; and legal divergence on AI-specific rules means per-region policy bundles in the guardrail layer. State the operating principle: content is regional, learnings are global — and document the boundary explicitly for auditors.",
  },
  {
    q: "Design a system where multiple specialized agents collaborate on long-running business workflows (days), surviving restarts and partial failures.",
    a: "Durable orchestration, agents as stateless workers: a workflow engine (Temporal-style) owns state — each agent invocation is a checkpointed activity with inputs/outputs persisted, so restarts resume from the last completed step, never re-running side effects (idempotency keys on all external actions). Agents communicate through typed artifacts in a shared store (structured claims, documents, decisions), not chat history — replayable and auditable. Long-running specifics: human approval steps as first-class workflow waits (days-long timers); versioning discipline so in-flight workflows survive prompt/agent upgrades (pin versions per workflow instance, or migration logic); compensation paths for partial failure (saga pattern — if step 7 fails, steps 1–6 may need business-level undo); and budget/deadline monitors that escalate stalled workflows to humans. Observability: the workflow trace IS the audit log. Anti-pattern to call out: keeping workflow state in the LLM's context window — context is a cache, never the source of truth.",
  },
  {
    q: "How do you design the human-in-the-loop layer so it actually catches errors instead of rubber-stamping?",
    a: "Design against attention decay: reviewers approve 99% of items and stop reading — so engineer friction where it matters. Techniques: risk-ranked queues (humans see the model's least-confident/highest-stakes items first, high-confidence low-stakes items batch or auto-approve — concentrating attention where it pays); diff-first UX (show what the AI changed/decided with evidence, not a wall of output); mandatory interaction for high-risk approvals (select the supporting evidence, not just click OK); seeded canaries (known-bad items injected to measure real catch rates per reviewer — if canaries pass, the review is theater and you know it); and feedback symmetry (reviewers see outcomes of their approvals, which maintains calibration). Measure review quality as a metric: catch rate on canaries, agreement rates, time-per-item distributions (too-fast flags rubber-stamping). Staff the truth: human review is a system to engineer, not a checkbox to claim.",
  },
  {
    q: "Design rate limiting and fair-use controls for an LLM API platform with wildly asymmetric request costs.",
    a: "Token-based, not request-based: a 100-token and 100k-token request differ 1000x in cost, so quotas meter tokens (input+output, with output estimated at admission and reconciled after) across windows — per-second burst, per-day budget. Layers: per-user and per-team quotas, per-model multipliers (frontier tokens cost more quota), and priority classes (interactive lanes get scheduling preference over batch; batch gets cheaper quota). Admission control under load: shed lowest-priority first, queue with backpressure signals (Retry-After), and protect TTFT SLOs for interactive traffic by capping long-prompt admissions per window. Fairness: weighted fair queuing across tenants at the inference scheduler, preventing one tenant's long generations from starving others — this is where naive gateways fail, because a request admitted is capacity held for its whole generation. Abuse: anomaly detection on token-consumption patterns. Expose usage APIs so teams self-monitor before hitting walls.",
  },
  {
    q: "You must add GenAI features to a 15-year-old monolith with no service infrastructure. Design the pragmatic path.",
    a: "Strangler pattern with an AI sidecar: stand up one new service (the AI gateway) beside the monolith — it owns model calls, prompts, evals, and guardrails; the monolith calls it over HTTP like any dependency. Nothing inside the monolith changes except thin integration points. Data: read replicas or CDC streams feed retrieval indexes — never let the AI service query production tables directly. Async-first integrations (queues for enrichment jobs) minimize latency coupling to the monolith's request cycle; synchronous features get strict timeouts with graceful degradation (feature simply doesn't appear). Team reality: the monolith team lacks LLM skills — the sidecar team owns AI quality, exposing dumb-simple contracts ('send text, get JSON'). Sequencing: first feature should be async and low-risk (e.g., draft suggestions) to build the pipeline; interactive features after the infrastructure is proven. The principle: modernize around the monolith, not through it.",
  },
  {
    q: "Design abuse prevention for a consumer AI product (free tier) — prompt farms, resellers, jailbreak communities.",
    a: "Economic and behavioral layers. Identity: device fingerprinting, phone/payment verification tiers gating free-tier depth — make account farming cost more than the compute it steals. Behavioral: per-account token velocity, entropy of usage patterns (farms look uniform), and shared-fingerprint clustering to catch distributed abuse; graduated response (slowdowns → captchas → verification walls → bans) rather than binary bans, which train evasion. Jailbreak handling: output-side safety classifiers catch what prompt-side misses; exploit signatures from monitoring feed regression suites; honeypot patterns identify coordinated probing. Reseller detection: API-like access patterns through consumer UX (steady QPS, no session variance) → route to commercial terms. Cost protection: free-tier compute budgeted per user per day with cheap-model routing. And measure the false-positive rate obsessively — punishing legitimate power users is how products die. Frame it: you're pricing compute, not moralizing usage.",
  },
  {
    q: "Design the architecture for A/B testing two foundation models behind one product, when responses differ stylistically.",
    a: "The contamination problem: users notice style shifts, and cross-model conversation history confuses both models. Design: sticky assignment per user for the experiment's duration; conversation continuity enforced (a conversation started on model A finishes on A, even post-experiment via pinning); and prompt adaptation per arm — each model gets its tuned prompt variant, because testing model B on model A's prompt measures prompt mismatch, not model quality. Fairness in judging: offline evals on both arms' outputs with a third-family judge (self-preference bias), online metrics that are style-robust (task completion, retention, edit rates — not thumbs, which correlate with verbosity). Cost normalization: report quality per dollar, not just quality. Duration: long enough to survive novelty effects. Infrastructure: this all falls out of the gateway + prompt registry + assignment service — if a candidate needs bespoke plumbing per experiment, the platform is underbuilt.",
  },
  {
    q: "Design 'AI SRE': monitoring and alerting for the AI layer itself across 30 production LLM features.",
    a: "Golden signals redefined per feature: quality (judge scores on sampled traffic, feedback rates, groundedness), integrity (parse-failure rate, refusal rate, guardrail trigger rate), performance (TTFT/total latency p99, queue depth), and economics (cost per request, token drift). Baselines and anomaly detection per feature — absolute thresholds fail across 30 heterogeneous features; alert on deviation from each feature's own baseline with seasonality. Canary probes: fixed golden queries per feature run every few minutes against production — catches provider-side model changes, index corruption, and prompt-deploy regressions before users do, with score-drop alarms. Attribution tooling: when quality drops, the first question is 'what changed' — automatic correlation against deploy events (prompt versions, model versions, index snapshots, provider status). Runbooks per alert class, ownership per feature, and a weekly quality review that treats drift like error budgets. The pitch: traditional APM sees latency and 200s; this layer sees meaning.",
  },
  {
    q: "Design a retrieval system when your 'documents' are a million short, contradictory, rapidly-changing records (support tickets, chat logs).",
    a: "The corpus fights RAG assumptions: individual records are noisy, contradictory, and low-authority. Design shifts: retrieve-then-aggregate — fetch many related records and synthesize consensus with recency weighting, rather than trusting top-3 chunks ('what do recent tickets say about X error' is an aggregation query); authority tiers (canonical KB articles outrank tickets; tickets are evidence of frequency, not truth); time decay in scoring, aggressive near-dupe clustering at index time (one incident spawns 200 near-identical tickets that would monopolize top-k — cluster and retrieve representatives with counts); and freshness pipeline in minutes, not days. Answer generation states its evidence basis ('based on 47 similar recent reports...'). Evals: time-sliced — retrieval quality measured against what was knowable at query time. The design insight: this is closer to analytics-over-text than document Q&A, and answering 'how many' or 'is this trending' means pairing the vector index with real aggregation queries.",
  },
  {
    q: "What's your framework for deciding agent autonomy levels in any system you design?",
    a: "Score each action on: reversibility (can it be undone cheaply?), blast radius (worst-case cost of a wrong action), verifiability (can correctness be checked automatically before/after?), and frequency (high-volume actions justify automation investment and provide statistical confidence). Map to a ladder: L0 suggest-only → L1 human executes → L2 auto with pre-approval rules → L3 auto with post-hoc review → L4 fully autonomous. Promotion between levels requires measured evidence at the current level (acceptance rates, error rates over N executions) — autonomy is earned per action type, not granted per agent. Reversible+verifiable+low-blast actions (draft an email, re-run a query) climb fast; irreversible or high-blast actions (send money, delete data, external comms) may cap at L2 permanently, by policy. Wrap with runtime enforcement (budgets, allowlists, kill switches) because the ladder is only as real as its enforcement layer. This framework answers half the agentic design questions in any interview — state it early and apply it consistently.",
  },
];
